name: custom actions
on:
  push:
    branches: [main]

jobs:
  testing-actions:
    runs-on: ubuntu-latest
    steps:
      - name: checkout files to vm
        uses: actions/checkout@v2.3.4

      - name: Custom docker action APIM
        uses: ./.github/actions/wso2apim/
        id: apim
        with:
          username: "Mihindu"
          password: ${{secrets.PASSWORD}}

      - run: |
          echo "It works!"
