name: custom actions
on:
  push:
    branches: [main]

jobs:
  testing-actions:
    runs-on: ubuntu-latest
    steps:
      - name: checkout files to vm
        uses: actions/checkout@v2.3.4

      # - name: Custom docker action APIM
      #   uses: ./.github/actions/wso2apim/
      #   id: apim
      #   with:
      #     usernameDevTenant: "mihindu@wso2.com@development"
      #     passwordDevTenant: ${{secrets.PASSWORD}}
      #     usernameProdTenant: "mihindu@wso2.com@production"
      #     passwordProdTenant: ${{secrets.PASSWORD}}
      #     APIProjectName: "SampleStore"
      #     OASJsonFilePath: "petstore.json"
      #     APIDefinitionFilePath: "api_template.yaml"
      #     APIVersion: "1.0.0"

      - name: APIM Cloud CICD from marketplace action
        uses: ./.github/actions/wso2apim/
        id: apim
        with:
          usernameDevTenant: "mihindu@wso2.com@development"
          passwordDevTenant: ${{secrets.PASSWORD}}
          usernameProdTenant: "mihindu@wso2.com@production"
          passwordProdTenant: ${{secrets.PASSWORD}}
          APIProjectName: "SampleStore"
          OASJsonFilePath: "petstore.json"
          APIDefinitionFilePath: "api_template.yaml"
          APIVersion: "1.0.0"

      - run: |
          echo "It works!"
